import avatar from 'src/assets/images/header/avatar.svg';

export const ARTISANData = [
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Online',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Offline',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Online',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Offline',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Online',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Offline',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Online',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Offline',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Online',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
	{
		name: 'Olajide Olajide',
		email: 'olajide@gmail.com',
		status: 'Offline',
		registrationDate: '06/05/2022',
		lastLogin: '06/05/2022',
		img: avatar,
	},
];
