import avatar from 'src/assets/images/header/avatar.svg';

export const BookingsData = [
	{
		id: 1,
		first_name: 'Olajide',
		last_name: 'Olajide',
		date: '2022-05-08',
		display_picture: avatar,
		status: 'Active',
	},
	{
		id: 2,
		first_name: 'Olajide',
		last_name: 'Olajide',
		date: '2022-09-08',
		display_picture: avatar,
		status: 'Resolved',
	},
	{
		id: 3,
		first_name: 'Olajide',
		last_name: 'Olajide',
		date: '2022-08-08',
		display_picture: avatar,
		status: 'Active',
	},
	{
		id: 4,
		first_name: 'Olajide',
		last_name: 'Olajide',
		date: '2021-03-11',
		display_picture: avatar,
		status: 'Resolved',
	},
	{
		id: 5,
		first_name: 'Olajide',
		last_name: 'Olajide',
		date: '2022-03-15',
		display_picture: avatar,
		status: 'Active',
	},
	{
		id: 6,
		first_name: 'Olajide',
		last_name: 'Olajide',
		date: '2022-06-08',
		display_picture: avatar,
		status: 'Resolved',
	},
	{
		id: 7,
		first_name: 'Olajide',
		last_name: 'Olajide',
		date: '2022-06-08',
		display_picture: avatar,
		status: 'Active',
	},
	{
		id: 8,
		first_name: 'Olajide',
		last_name: 'Olajide',
		date: '2022-07-08',
		display_picture: avatar,
		status: 'Resolved',
	},
];
