import avatar from 'src/assets/images/header/avatar.svg';

export const CustomerData = [
	{
		id: 1,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Voters Card',
		date: '2022-05-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		gender: 'Male',
	},
	{
		id: 2,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Voters Card',
		date: '2022-09-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		gender: 'Male',
	},
	{
		id: 3,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Voters Card',
		date: '2022-08-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Upgrade',
		gender: 'Female',
	},
	{
		id: 4,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Drivers Licence',
		date: '2021-03-11',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		gender: 'Male',
	},
	{
		id: 5,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Drivers Licence',
		date: '2022-03-15',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Upgrade',
		gender: 'Female',
	},
	{
		id: 6,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Voters Card',
		date: '2022-06-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		gender: 'Male',
	},
	{
		id: 7,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Drivers Licence',
		date: '2022-06-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Upgrade',
		gender: 'Female',
	},
	{
		id: 8,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Drivers Licence',
		date: '2022-07-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		gender: 'Male',
	},
];

export const VendorData = [
	{
		id: 1,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Voters Card',
		date: '2022-05-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		occupation: 'Barber',
		gender: 'Female',
	},
	{
		id: 2,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Voters Card',
		date: '2022-09-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		occupation: 'Barber',
		gender: 'Male',
	},
	{
		id: 3,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Voters Card',
		date: '2022-08-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Upgrade',
		occupation: 'Barber',
		gender: 'Female',
	},
	{
		id: 4,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Drivers Licence',
		date: '2021-03-11',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		occupation: 'Barber',
		gender: 'Male',
	},
	{
		id: 5,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Drivers Licence',
		date: '2022-03-15',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Upgrade',
		occupation: 'Barber',
		gender: 'Female',
	},
	{
		id: 6,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Voters Card',
		date: '2022-06-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		occupation: 'Barber',
		gender: 'Male',
	},
	{
		id: 7,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Drivers Licence',
		date: '2022-06-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Upgrade',
		occupation: 'Barber',
		gender: 'Female',
	},
	{
		id: 8,
		first_name: 'Olajide',
		last_name: 'Olajide',
		meansOfId: 'Drivers Licence',
		date: '2022-07-08',
		display_picture: avatar,
		email: 'email@gmail.com',
		status: 'Pending',
		occupation: 'Barber',
		gender: 'Male',
	},
];
